import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Bridges Chain',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark scroll-smooth' dir='ltr'>
      <body className="font-urbanist text-base text-black dark:text-white dark:bg-slate-900">{children}</body>
    </html>
  )
}
